
class ServerCommands:
  PAUSE_REQUESTER = 'PAUSE_REQUESTER'
  RESUME_REQUESTER = 'RESUME_REQUESTER'
  SKIP_REDRAW = 'SKIP_REDRAW'
  RESET_DRAWER = 'RESET_DRAWER'
  RESET_LICENSE = 'RESET_LICENSE'
  DISABLE_FOR_SESSION = 'DISABLE_FOR_SESSION'
  ENABLE_FOR_SESSION = 'ENABLE_FOR_SESSION'
  BLOCK_LICENSE = 'BLOCK_LICENSE'


POSITION_WOTSTAT_EVENT_ENTER_LICENSE = 'POSITION_WOTSTAT_EVENT_ENTER_LICENSE'
POSITION_WOTSTAT_EVENT_RESET_LICENSE = 'POSITION_WOTSTAT_EVENT_RESET_LICENSE'

class PlayerPrefsKeys:
  LAST_VERSION = 'lastVersion'
  LICENSE = 'license'
  TOKEN = 'token'